### ISSUE TITLE
Something is broken on v1.1.0

### ISSUE THREAD

**Issue by alexandreapis** [vinorodrigues/bootstrap-dark-5#33] opened 2021-08-31 14:41 UTC
Since the last update, something is not working as expected... until v.1.0.2 everything was working fine...

I think there's something wrong with color inversion...

Look at the examples... both light and dark modes are practically unusable:

https://vinorodrigues.github.io/bootstrap-dark-5/examples/cheatsheet-night.html
https://vinorodrigues.github.io/bootstrap-dark-5/examples/cheatsheet-nightshade.html
https://vinorodrigues.github.io/bootstrap-dark-5/examples/cheatsheet-dark.html

Happens in any browser and OS

**Comment by vinorodrigues** [comment] 2021-08-31 19:47
Also broken in Boostrap core!  see https://getbootstrap.com/docs/5.1/examples/cheatsheet/

**Comment by vinorodrigues** [comment] 2021-08-31 19:59
class def for `.bg-body` has changed since the rgba vars were added, `.bg-body` used to be the "background-color", but now its the "color", i.e. same as the text color.
This is only a problem in the cheatsheet examples, I'll remove that class in the content to fix it.

**Comment by vinorodrigues** [comment] 2021-08-31 20:22
`-nightshade` and `-blackbox` variants still broken.  I'll look at these soon.

**Comment by alexandreapis** [comment] 2021-08-31 20:31
Ok, thanks... I'm using nightshade, so I'll wait.. take a look at my website comparison using both versions

v1.0.2:
![image](https://user-images.githubusercontent.com/21248634/131571552-79435098-770d-419f-87dd-f35b8a11d8a9.png)

v1.1.0:
![image](https://user-images.githubusercontent.com/21248634/131571661-4efba008-1445-436d-9786-64eae143516c.png)

**Comment by vinorodrigues** [comment] 2021-09-01 09:13
I found the problem (but not a fix, yet).

BS 5.1.0 added, according to the commit message, "

So most file CSS will have:
```scss
:root {
  color: var(--#{$variable-prefix}body-color);
  background-color: var(--#{$variable-prefix}body-bg); // 2
}
```

The problem is that `:root` cannot have a css selector.  Neither  `:root html.dark {}`, nor `:html.dark root {}` work (or are ignored).

I need to think this one through for a fix.

**Comment by vinorodrigues** [comment] 2021-09-01 11:10
Ok - resolution was to revert back to pre-5.1 declarations of `body` colors.  Please try the latest commit on this.

**Comment by vinorodrigues** [comment] 2021-09-01 11:13
fair warning ... there is going to be more inconsistencies, basically anything that uses `:roor` css variables will not work.

**Comment by vinorodrigues** [comment] 2021-09-02 09:47
This is far more difficult to fix than I thought - see my note in the [README.md](https://github.com/vinorodrigues/bootstrap-dark-5/blob/main/README.md) on this.  Closing this.

**Closed by vinorodrigues** 2021-09-02 09:47 UTC

**Comment by vinorodrigues** [comment] 2021-10-04 05:10
See [comments](https://github.com/vinorodrigues/bootstrap-dark-5/issues/35#issuecomment-933146545) on issue #35.
